insert into career (name, code) values ('Informática Aplicada - Plan 60', 'PLAN60');
insert into career (name, code) values ('Control Eléctrico y Accionamientos - Plan 61', 'PLAN61');
insert into career (name, code) values ('Mecánica, Automotores y Máquinas Térmicas - Plan 62', 'PLAN62');
insert into career (name, code) values ('Automatización y Robótica - Plan 63', 'PLAN63');
insert into career (name, code) values ('Electrónica - Plan 64', 'PLAN64');
insert into career (name, code) values ('Química y Química Aplicada - Plan 65', 'PLAN65');
insert into career (name, code) values ('Física y Física Aplicada - Plan 66', 'PLAN66');
insert into career (name, code) values ('Diseño Tecnológico - Plan 67', 'PLAN67');
insert into career (name, code) values ('Profesorado en Disciplinas Industriales - Plan 68', 'PLAN68');
insert into career (name, code) values ('Inglés e Inglés Técnico - Plan 69', 'PLAN69');
insert into career (name, code) values ('Matemática y Matemática Aplicada - Plan 70', 'PLAN70');